<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Online;

use GrabPay\Merchant\Models\DTO;

class ChargeInitData extends DTO
{
    /**
     * Partner transaction ID used as the idempotency key for subsequent API calls.
     */
    public string $partnerTxID;

    /**
     * This is the transaction ID generated by Grab and encoded in JWT token format.
     * Specify this value as a request URL parameter when constructing the Web URL to Grab web page.
     */
    public string $request;
}