<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Online;

use GrabPay\Merchant\Models\DTO;

class ChargeInitParams extends DTO
{
    /**
     * Transaction amount as integer.
     * A positive integer in the smallest currency unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency).
     */
    public int $amount;

    /**
     * Currency that is associated with the payment amount.
     * Specify the three-letter ISO 4217 currency code.
     */
    public string $currency;

    /**
     * Description of the charge.
     */
    public string $description;

    /**
     * Hides the specified payment method from the user during the GrabPay Checkout flow.
     * If this is not set, GrabPay presents all eligible payment methods to the user.
     * However, note that you cannot hide the GrabPay Wallet payment method.
     */
    public ?array $hidePaymentMethods;

    /**
     * The items to be charged for.
     *
     * @var \GrabPay\Merchant\Models\Online\Item[]
     */
    public $items = [];

    /**
     * Required if used for PayLater Instalment transactions.
     * Otherwise it is optional.
     * Additional information related to the current transaction.
     */
    public ?MetaInfo $metaInfo;

    /**
     * This is the unique identifier of each transaction generated by the partner.
     * Each transaction might consist of several charges.
     * Usually the value is a single receipt ID from the partner and can be displayed to the user.
     */
    public string $partnerGroupTxID;

    /**
     * The partner's transaction ID.
     */
    public string $partnerTxID;

    /**
     * Sharing recommended attributes will help Grab in better evaluating and approving the PayLater transaction, and create a better overall experience for your customers.
     */
    public ?ShippingDetails $shippingDetails;
}