<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Offline;

use GrabPay\Merchant\Models\DTO;

class CancelTxnParams extends DTO
{
    /**
     * Currency that is associated with the payment amount.
     * Specify the three-letter ISO currency code following the ISO 4217 standard.
     */
    public string $currency;

    /**
     * The UUID of the request with a fixed length of 32 characters.
     */
    public string $msgID;

    /**
     * The original transaction order number generated by the terminal with a fixed length of 32 characters.
     */
    public string $origPartnerTxID;
}