<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Offline;

use GrabPay\Merchant\Models\DTO;

class GetTxnDetailsData extends DTO
{
    /**
     * An array of JSON object modifier.
     * The key value pair of additional information requested.
     */
    public ?AdditionalInfo $additionalInfo;

    /**
     * Transaction amount as integer.
     * A positive integer in the smallest currency unit, with no decimal point.
     */
    public int $amount;

    /**
     * The transaction currency code following the ISO 4217 currency code standard.
     */
    public string $currency;

    /**
     * An error message for failed transactions.
     */
    public ?string $errMsg;

    /**
     * The UUID of the request with a fixed length of 32 characters.
     */
    public string $msgID;

    /**
     * The status of the transaction.
     */
    public string $status;

    /**
     * A unique transaction ID generated by GrabPay.
     */
    public string $txID;

    /**
     * The Unix timestamp of the updatated time of transactions.
     */
    public int $updated;
}