<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Offline;

use GrabPay\Merchant\Models\DTO;

class RefundTxnData extends DTO
{
    /**
     * An array of JSON object modifier.
     * The key value pair of additional information requested.
     */
    public ?AdditionalInfo $additionalInfo;

    /**
     * Provides additional information about the status.
     * Returns empty when status = success.
     */
    public string $description;

    /**
     * Message
     */
    public string $msg;

    /**
     * The UUID of the request with a fixed length of 32 characters.
     */
    public string $msgID;

    /**
     * The original transaction order number generated by GrabPay.
     */
    public string $originTxID;

    /**
     * The status of the transaction.
     */
    public string $status;

    /**
     * A unique transaction ID generated by GrabPay.
     */
    public string $txID;
}