<?php

declare(strict_types=1);

namespace GrabPay\Merchant\Models\Offline;

use GrabPay\Merchant\Models\DTO;

class RefundTxnParams extends DTO
{
    /**
     * Transaction amount as integer.
     * A positive integer in the smallest currency unit, with no decimal point.
     */
    public int $amount;

    /**
     * Currency that is associated with the payment amount.
     * Specify the three-letter ISO currency code following the ISO 4217 standard.
     */
    public string $currency;

    /**
     * The UUID of the request with a fixed length of 32 characters.
     */
    public string $msgID;

    /**
     * The original transaction order number generated by the terminal with a fixed length of 32 characters.
     */
    public string $origPartnerTxID;

    /**
     * A unique number denoting this refund transaction, generated by the terminal with a fixed length of 32 characters.
     */
    public string $partnerTxID;

    /**
     * The reason explaining the refund.
     */
    public string $reason;
}