package com.merchantsdk.payment.config;

public enum PathUtility {
    PATH_OAUTH_TOKEN,
    PATH_POS_CREATE_QR_CODE,
    PATH_POS_CANCEL_TRANSACTION,
    PATH_POS_REFUND_TRANSACTION,
    PATH_POS_PERFORM_TRANSACTION,
    PATH_POS_TRANSACTION_DETAILS,

    PATH_ONA_CHARGE_INIT,
    PATH_ONA_CHARGE_COMPLETE,
    PATH_ONA_CHARGE_STATUS,
    PATH_ONA_REFUND,
    PATH_ONA_REFUND_STATUS,
    PATH_ONA_ONE_TIME_CHARGE_STATUS
}
