package com.merchantsdk.payment.models;

/**
 * PosInitRequest
 * <p>
 * 
 * 
 */
public class PosInitiateRequest {
    public static class PosDetails {

        /**
         * consumerIdentifier
         * <p>
         * This field is the consumer identifier derived from scanning the barcode or
         * the QR code flashed by the consumer during payment.
         * <br/>
         * *This field is only required when paymentChannel in the request is "CPQR".
         * 
         */
        private String consumerIdentifier;

        /**
         * consumerIdentifier
         * <p>
         * This field is the consumer identifier derived from scanning the barcode or
         * the QR code flashed by the consumer during payment.
         * <br/>
         * *This field is only required when paymentChannel in the request is "CPQR".
         * 
         */
        public String getConsumerIdentifier() {
            return consumerIdentifier;
        }

        /**
         * consumerIdentifier
         * <p>
         * This field is the consumer identifier derived from scanning the barcode or
         * the QR code flashed by the consumer during payment.
         * <br/>
         * *This field is only required when paymentChannel in the request is "CPQR".
         * 
         */
        public void setConsumerIdentifier(String consumerIdentifier) {
            this.consumerIdentifier = consumerIdentifier;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(PosDetails.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this)))
                    .append('[');
            sb.append(',');
            sb.append("consumerIdentifier");
            sb.append('=');
            sb.append(((this.consumerIdentifier == null) ? "<null>" : this.consumerIdentifier));
            sb.append(',');
            if (sb.charAt((sb.length() - 1)) == ',') {
                sb.setCharAt((sb.length() - 1), ']');
            } else {
                sb.append(']');
            }
            return sb.toString();
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = ((result * 31) + ((this.consumerIdentifier == null) ? 0 : this.consumerIdentifier.hashCode()));
            return result;
        }

        @Override
        public boolean equals(Object other) {
            if (other == this) {
                return true;
            }
            if ((other instanceof PosDetails) == false) {
                return false;
            }
            PosDetails rhs = ((PosDetails) other);
            return ((this.consumerIdentifier == rhs.consumerIdentifier)
                    || ((this.consumerIdentifier != null) && this.consumerIdentifier.equals(rhs.consumerIdentifier)));
        }

    }

    public static class TransactionDetails {

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * (Required)
         * 
         */
        private PosPaymentChannel paymentChannel;

        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * (Required)
         * 
         */
        private String partnerTxID;
        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        private String partnerGroupTxID;
        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        private String billRefNumber;
        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * (Required)
         * 
         */
        private Long amount;
        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * (Required)
         * 
         */
        private Currency currency;

        private Long paymentExpiryTime;

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * (Required)
         * 
         */
        public PosPaymentChannel getPaymentChannel() {
            return paymentChannel;
        }

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * (Required)
         * 
         */
        public void setPaymentChannel(PosPaymentChannel paymentChannel) {
            this.paymentChannel = paymentChannel;
        }

        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * (Required)
         * 
         */
        public String getPartnerTxID() {
            return partnerTxID;
        }

        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * (Required)
         * 
         */
        public void setPartnerTxID(String partnerTxID) {
            this.partnerTxID = partnerTxID;
        }

        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        public String getPartnerGroupTxID() {
            return partnerGroupTxID;
        }

        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        public void setPartnerGroupTxID(String partnerGroupTxID) {
            this.partnerGroupTxID = partnerGroupTxID;
        }

        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        public String getBillRefNumber() {
            return billRefNumber;
        }

        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        public void setBillRefNumber(String billRefNumber) {
            this.billRefNumber = billRefNumber;
        }

        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * (Required)
         * 
         */
        public Long getAmount() {
            return amount;
        }

        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * (Required)
         * 
         */
        public void setAmount(Long amount) {
            this.amount = amount;
        }

        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * (Required)
         * 
         */
        public Currency getCurrency() {
            return currency;
        }

        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * (Required)
         * 
         */
        public void setCurrency(Currency currency) {
            this.currency = currency;
        }

        public Long getPaymentExpiryTime() {
            return paymentExpiryTime;
        }

        public void setPaymentExpiryTime(Long paymentExpiryTime) {
            this.paymentExpiryTime = paymentExpiryTime;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(TransactionDetails.class.getName()).append('@')
                    .append(Integer.toHexString(System.identityHashCode(this))).append('[');
            sb.append("paymentChannel");
            sb.append('=');
            sb.append(((this.paymentChannel == null) ? "<null>" : this.paymentChannel));
            sb.append(',');
            sb.append(',');
            sb.append("partnerTxID");
            sb.append('=');
            sb.append(((this.partnerTxID == null) ? "<null>" : this.partnerTxID));
            sb.append(',');
            sb.append("partnerGroupTxID");
            sb.append('=');
            sb.append(((this.partnerGroupTxID == null) ? "<null>" : this.partnerGroupTxID));
            sb.append(',');
            sb.append("billRefNumber");
            sb.append('=');
            sb.append(((this.billRefNumber == null) ? "<null>" : this.billRefNumber));
            sb.append(',');
            sb.append("amount");
            sb.append('=');
            sb.append(((this.amount == null) ? "<null>" : this.amount));
            sb.append(',');
            sb.append("currency");
            sb.append('=');
            sb.append(((this.currency == null) ? "<null>" : this.currency));
            sb.append(',');
            if (sb.charAt((sb.length() - 1)) == ',') {
                sb.setCharAt((sb.length() - 1), ']');
            } else {
                sb.append(']');
            }
            return sb.toString();
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = ((result * 31) + ((this.amount == null) ? 0 : this.amount.hashCode()));
            result = ((result * 31) + ((this.currency == null) ? 0 : this.currency.hashCode()));
            result = ((result * 31) + ((this.billRefNumber == null) ? 0 : this.billRefNumber.hashCode()));
            result = ((result * 31) + ((this.partnerTxID == null) ? 0 : this.partnerTxID.hashCode()));
            result = ((result * 31) + ((this.partnerGroupTxID == null) ? 0 : this.partnerGroupTxID.hashCode()));
            result = ((result * 31) + ((this.paymentChannel == null) ? 0 : this.paymentChannel.hashCode()));
            return result;
        }

        @Override
        public boolean equals(Object other) {
            if (other == this) {
                return true;
            }
            if ((other instanceof TransactionDetails) == false) {
                return false;
            }
            TransactionDetails rhs = ((TransactionDetails) other);
            return ((((((((this.amount == rhs.amount) || ((this.amount != null) && this.amount.equals(rhs.amount)))
                    && ((this.currency == rhs.currency)
                            || ((this.currency != null) && this.currency.equals(rhs.currency))))
                    && ((this.billRefNumber == rhs.billRefNumber)
                            || ((this.billRefNumber != null) && this.billRefNumber.equals(rhs.billRefNumber))))
                    && ((this.partnerTxID == rhs.partnerTxID)
                            || ((this.partnerTxID != null) && this.partnerTxID.equals(rhs.partnerTxID))))
                    && ((this.partnerGroupTxID == rhs.partnerGroupTxID)
                            || ((this.partnerGroupTxID != null) && this.partnerGroupTxID.equals(rhs.partnerGroupTxID))))
                    && ((this.paymentChannel == rhs.paymentChannel)
                            || ((this.paymentChannel != null) && this.paymentChannel.equals(rhs.paymentChannel)))));
        }

    }

    private TransactionDetails transactionDetails;
    private PaymentMethod paymentMethod;
    private PosDetails posDetails;

    public TransactionDetails getTransactionDetails() {
        return transactionDetails;
    }

    public void setTransactionDetails(TransactionDetails transactionDetails) {
        this.transactionDetails = transactionDetails;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public PosDetails getPOSDetails() {
        return posDetails;
    }

    public void setPOSDetails(PosDetails posDetails) {
        this.posDetails = posDetails;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(PosInitiateRequest.class.getName()).append('@')
                .append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("transactionDetails");
        sb.append('=');
        sb.append(((this.transactionDetails == null) ? "<null>" : this.transactionDetails));
        sb.append(',');
        sb.append("paymentMethod");
        sb.append('=');
        sb.append(((this.paymentMethod == null) ? "<null>" : this.paymentMethod));
        sb.append(',');
        sb.append("posDetails");
        sb.append('=');
        sb.append(((this.posDetails == null) ? "<null>" : this.posDetails));
        sb.append(',');
        if (sb.charAt((sb.length() - 1)) == ',') {
            sb.setCharAt((sb.length() - 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result * 31) + ((this.transactionDetails == null) ? 0 : this.transactionDetails.hashCode()));
        result = ((result * 31) + ((this.paymentMethod == null) ? 0 : this.paymentMethod.hashCode()));
        result = ((result * 31) + ((this.posDetails == null) ? 0 : this.posDetails.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof PosInitiateRequest) == false) {
            return false;
        }
        PosInitiateRequest rhs = ((PosInitiateRequest) other);
        return ((((this.transactionDetails == rhs.transactionDetails)
                || ((this.transactionDetails != null) && this.transactionDetails.equals(rhs.transactionDetails)))
                && ((this.paymentMethod == rhs.paymentMethod)
                        || ((this.paymentMethod != null) && this.paymentMethod.equals(rhs.paymentMethod))))
                && ((this.posDetails == rhs.posDetails)
                        || ((this.posDetails != null) && this.posDetails.equals(rhs.posDetails))));
    }

}
