package com.merchantsdk.payment.models;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * PosInqResponse
 * <p>
 * 
 * 
 */
public class PosInquiryResponse {
    public static class TransactionDetails {

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * 
         */
        private PosPaymentChannel paymentChannel;
        /**
         * storeGrabID
         * <p>
         * This field is the unique store identifier issued by Grab to the merchant.
         * 
         */
        private String storeGrabID;
        /**
         * Transaction type
         * <p>
         * This field will differentiate a payment inquiry from a refund inquiry.
         * 
         */
        private TxType txType;
        /**
         * grabTxID
         * <p>
         * This field contains the unique transaction reference number issued by Grab.
         * This field will be idempotent to Grab.
         * 
         */
        private String grabTxID;
        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * 
         */
        private String partnerTxID;
        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        private String partnerGroupTxID;
        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        private String billRefNumber;
        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * 
         */
        private Long amount;
        /**
         * This field contains the sum of past refund amounts, which is a positive
         * integer in the smallest currency unit, with no decimal point i.e., $123.45
         * will be passed in as 12345 in this field.
         * 
         */
        private Long refundedAmount;
        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * 
         */
        private Currency currency;
        /**
         * Payment Method
         * <p>
         * Returns one of the enum values.
         * 
         * `CARD` is only applicable to Thailand.
         * 
         * `PAYNOW`, `DUITNOW`, `QRPH` are only applicable to POS API.
         * (Required)
         * 
         */
        private PosPaymentMethod paymentMethod;
        /**
         * This field contains the time which the transaction was last updated in Grab's
         * system. For a successful transaction, this will be the time where Grab
         * registers the transaction in its system. This field will be in Unix Epoch
         * time.
         * (Required)
         * 
         */
        private Long updatedTime;
        /**
         * paymentExpiryTime
         * <p>
         * This will allow both the merchant's and Grab's systems to expire the
         * transaction after a specified time. This field will be in Unix Epoch time.
         * 
         */
        private Long paymentExpiryTime;

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * 
         */
        public PosPaymentChannel getPaymentChannel() {
            return paymentChannel;
        }

        /**
         * Payment channel
         * <p>
         * This field will be used to differentiate the different POS payment channels,
         * and will determine which other Conditional parameters will need to be
         * required in the request, or processed in the response.
         * 
         */
        public void setPaymentChannel(PosPaymentChannel paymentChannel) {
            this.paymentChannel = paymentChannel;
        }

        /**
         * storeGrabID
         * <p>
         * This field is the unique store identifier issued by Grab to the merchant.
         * 
         */
        public String getStoreGrabID() {
            return storeGrabID;
        }

        /**
         * storeGrabID
         * <p>
         * This field is the unique store identifier issued by Grab to the merchant.
         * 
         */
        public void setStoreGrabID(String storeGrabID) {
            this.storeGrabID = storeGrabID;
        }

        /**
         * Transaction type
         * <p>
         * This field will differentiate a payment inquiry from a refund inquiry.
         * 
         */
        public TxType getTxType() {
            return txType;
        }

        /**
         * Transaction type
         * <p>
         * This field will differentiate a payment inquiry from a refund inquiry.
         * 
         */
        public void setTxType(TxType txType) {
            this.txType = txType;
        }

        /**
         * grabTxID
         * <p>
         * This field contains the unique transaction reference number issued by Grab.
         * This field will be idempotent to Grab.
         * 
         */
        public String getGrabTxID() {
            return grabTxID;
        }

        /**
         * grabTxID
         * <p>
         * This field contains the unique transaction reference number issued by Grab.
         * This field will be idempotent to Grab.
         * 
         */
        public void setGrabTxID(String grabTxID) {
            this.grabTxID = grabTxID;
        }

        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * 
         */
        public String getPartnerTxID() {
            return partnerTxID;
        }

        /**
         * paymentTxID
         * <p>
         * The partner's transaction ID.
         * 
         */
        public void setPartnerTxID(String partnerTxID) {
            this.partnerTxID = partnerTxID;
        }

        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        public String getPartnerGroupTxID() {
            return partnerGroupTxID;
        }

        /**
         * partnerGroupTxID
         * <p>
         * This is the unique identifier of each transaction generated by the partner.
         * Each transaction might consist of several charges. Usually the value is a
         * single receipt ID from the partner and can be displayed to the user.
         * 
         */
        public void setPartnerGroupTxID(String partnerGroupTxID) {
            this.partnerGroupTxID = partnerGroupTxID;
        }

        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        public String getBillRefNumber() {
            return billRefNumber;
        }

        /**
         * billRefNumber
         * <p>
         * This field can be used to define the Bill Reference Number when a merchant is
         * receiving payments via a Grab wallet, or non-Grab wallet. When this field is
         * not sent in the request, consumers will be able to enter the reference number
         * themselves in the respective payment app.
         * 
         */
        public void setBillRefNumber(String billRefNumber) {
            this.billRefNumber = billRefNumber;
        }

        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * 
         */
        public Long getAmount() {
            return amount;
        }

        /**
         * amount
         * <p>
         * Transaction amount as integer. A positive integer in the smallest currency
         * unit (e.g., 100 cents to charge S$1.00, a zero-decimal currency). For
         * example, S$5.34 will be represented as 534.
         * 
         */
        public void setAmount(Long amount) {
            this.amount = amount;
        }

        /**
         * This field contains the sum of past refund amounts, which is a positive
         * integer in the smallest currency unit, with no decimal point i.e., $123.45
         * will be passed in as 12345 in this field.
         * 
         */
        public Long getRefundedAmount() {
            return refundedAmount;
        }

        /**
         * This field contains the sum of past refund amounts, which is a positive
         * integer in the smallest currency unit, with no decimal point i.e., $123.45
         * will be passed in as 12345 in this field.
         * 
         */
        public void setRefundedAmount(Long refundedAmount) {
            this.refundedAmount = refundedAmount;
        }

        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * 
         */
        public Currency getCurrency() {
            return currency;
        }

        /**
         * currency
         * <p>
         * Currency that is associated with the payment amount. Specify the three-letter
         * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
         * 
         * 
         */
        public void setCurrency(Currency currency) {
            this.currency = currency;
        }

        /**
         * Payment Method
         * <p>
         * Returns one of the enum values.
         * 
         * `CARD` is only applicable to Thailand.
         * 
         * `PAYNOW`, `DUITNOW`, `QRPH` are only applicable to POS API.
         * (Required)
         * 
         */
        public PosPaymentMethod getPaymentMethod() {
            return paymentMethod;
        }

        /**
         * Payment Method
         * <p>
         * Returns one of the enum values.
         * 
         * `CARD` is only applicable to Thailand.
         * 
         * `PAYNOW`, `DUITNOW`, `QRPH` are only applicable to POS API.
         * (Required)
         * 
         */
        public void setPaymentMethod(PosPaymentMethod paymentMethod) {
            this.paymentMethod = paymentMethod;
        }

        /**
         * This field contains the time which the transaction was last updated in Grab's
         * system. For a successful transaction, this will be the time where Grab
         * registers the transaction in its system. This field will be in Unix Epoch
         * time.
         * (Required)
         * 
         */
        public Long getUpdatedTime() {
            return updatedTime;
        }

        /**
         * This field contains the time which the transaction was last updated in Grab's
         * system. For a successful transaction, this will be the time where Grab
         * registers the transaction in its system. This field will be in Unix Epoch
         * time.
         * (Required)
         * 
         */
        public void setUpdatedTime(Long updatedTime) {
            this.updatedTime = updatedTime;
        }

        /**
         * paymentExpiryTime
         * <p>
         * This will allow both the merchant's and Grab's systems to expire the
         * transaction after a specified time. This field will be in Unix Epoch time.
         * 
         */
        public Long getPaymentExpiryTime() {
            return paymentExpiryTime;
        }

        /**
         * paymentExpiryTime
         * <p>
         * This will allow both the merchant's and Grab's systems to expire the
         * transaction after a specified time. This field will be in Unix Epoch time.
         * 
         */
        public void setPaymentExpiryTime(Long paymentExpiryTime) {
            this.paymentExpiryTime = paymentExpiryTime;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(TransactionDetails.class.getName()).append('@')
                    .append(Integer.toHexString(System.identityHashCode(this))).append('[');
            sb.append("paymentChannel");
            sb.append('=');
            sb.append(((this.paymentChannel == null) ? "<null>" : this.paymentChannel));
            sb.append(',');
            sb.append("storeGrabID");
            sb.append('=');
            sb.append(((this.storeGrabID == null) ? "<null>" : this.storeGrabID));
            sb.append(',');
            sb.append("txType");
            sb.append('=');
            sb.append(((this.txType == null) ? "<null>" : this.txType));
            sb.append(',');
            sb.append("grabTxID");
            sb.append('=');
            sb.append(((this.grabTxID == null) ? "<null>" : this.grabTxID));
            sb.append(',');
            sb.append("partnerTxID");
            sb.append('=');
            sb.append(((this.partnerTxID == null) ? "<null>" : this.partnerTxID));
            sb.append(',');
            sb.append("partnerGroupTxID");
            sb.append('=');
            sb.append(((this.partnerGroupTxID == null) ? "<null>" : this.partnerGroupTxID));
            sb.append(',');
            sb.append("billRefNumber");
            sb.append('=');
            sb.append(((this.billRefNumber == null) ? "<null>" : this.billRefNumber));
            sb.append(',');
            sb.append("amount");
            sb.append('=');
            sb.append(((this.amount == null) ? "<null>" : this.amount));
            sb.append(',');
            sb.append("refundedAmount");
            sb.append('=');
            sb.append(((this.refundedAmount == null) ? "<null>" : this.refundedAmount));
            sb.append(',');
            sb.append("currency");
            sb.append('=');
            sb.append(((this.currency == null) ? "<null>" : this.currency));
            sb.append(',');
            sb.append("paymentMethod");
            sb.append('=');
            sb.append(((this.paymentMethod == null) ? "<null>" : this.paymentMethod));
            sb.append(',');
            sb.append("updatedTime");
            sb.append('=');
            sb.append(((this.updatedTime == null) ? "<null>" : this.updatedTime));
            sb.append(',');
            sb.append("paymentExpiryTime");
            sb.append('=');
            sb.append(((this.paymentExpiryTime == null) ? "<null>" : this.paymentExpiryTime));
            sb.append(',');
            if (sb.charAt((sb.length() - 1)) == ',') {
                sb.setCharAt((sb.length() - 1), ']');
            } else {
                sb.append(']');
            }
            return sb.toString();
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = ((result * 31) + ((this.updatedTime == null) ? 0 : this.updatedTime.hashCode()));
            result = ((result * 31) + ((this.amount == null) ? 0 : this.amount.hashCode()));
            result = ((result * 31) + ((this.paymentExpiryTime == null) ? 0 : this.paymentExpiryTime.hashCode()));
            result = ((result * 31) + ((this.txType == null) ? 0 : this.txType.hashCode()));
            result = ((result * 31) + ((this.billRefNumber == null) ? 0 : this.billRefNumber.hashCode()));
            result = ((result * 31) + ((this.paymentChannel == null) ? 0 : this.paymentChannel.hashCode()));
            result = ((result * 31) + ((this.storeGrabID == null) ? 0 : this.storeGrabID.hashCode()));
            result = ((result * 31) + ((this.grabTxID == null) ? 0 : this.grabTxID.hashCode()));
            result = ((result * 31) + ((this.paymentMethod == null) ? 0 : this.paymentMethod.hashCode()));
            result = ((result * 31) + ((this.currency == null) ? 0 : this.currency.hashCode()));
            result = ((result * 31) + ((this.partnerTxID == null) ? 0 : this.partnerTxID.hashCode()));
            result = ((result * 31) + ((this.partnerGroupTxID == null) ? 0 : this.partnerGroupTxID.hashCode()));
            result = ((result * 31) + ((this.refundedAmount == null) ? 0 : this.refundedAmount.hashCode()));
            return result;
        }

        @Override
        public boolean equals(Object other) {
            if (other == this) {
                return true;
            }
            if ((other instanceof TransactionDetails) == false) {
                return false;
            }
            TransactionDetails rhs = ((TransactionDetails) other);
            return ((((((((((((((this.updatedTime == rhs.updatedTime)
                    || ((this.updatedTime != null) && this.updatedTime.equals(rhs.updatedTime)))
                    && ((this.amount == rhs.amount) || ((this.amount != null) && this.amount.equals(rhs.amount))))
                    && ((this.paymentExpiryTime == rhs.paymentExpiryTime)
                            || ((this.paymentExpiryTime != null)
                                    && this.paymentExpiryTime.equals(rhs.paymentExpiryTime))))
                    && ((this.txType == rhs.txType) || ((this.txType != null) && this.txType.equals(rhs.txType))))
                    && ((this.billRefNumber == rhs.billRefNumber)
                            || ((this.billRefNumber != null) && this.billRefNumber.equals(rhs.billRefNumber))))
                    && ((this.paymentChannel == rhs.paymentChannel)
                            || ((this.paymentChannel != null) && this.paymentChannel.equals(rhs.paymentChannel))))
                    && ((this.storeGrabID == rhs.storeGrabID)
                            || ((this.storeGrabID != null) && this.storeGrabID.equals(rhs.storeGrabID))))
                    && ((this.grabTxID == rhs.grabTxID)
                            || ((this.grabTxID != null) && this.grabTxID.equals(rhs.grabTxID))))
                    && ((this.paymentMethod == rhs.paymentMethod)
                            || ((this.paymentMethod != null) && this.paymentMethod.equals(rhs.paymentMethod))))
                    && ((this.currency == rhs.currency)
                            || ((this.currency != null) && this.currency.equals(rhs.currency))))
                    && ((this.partnerTxID == rhs.partnerTxID)
                            || ((this.partnerTxID != null) && this.partnerTxID.equals(rhs.partnerTxID))))
                    && ((this.partnerGroupTxID == rhs.partnerGroupTxID)
                            || ((this.partnerGroupTxID != null) && this.partnerGroupTxID.equals(rhs.partnerGroupTxID))))
                    && ((this.refundedAmount == rhs.refundedAmount)
                            || ((this.refundedAmount != null) && this.refundedAmount.equals(rhs.refundedAmount))));
        }
    }

    /**
     * Transaction type
     * <p>
     * This field will differentiate a payment inquiry from a refund inquiry.
     * 
     */
    public static enum TxType {

        PAYMENT("PAYMENT"),
        REFUND("REFUND");

        private final String value;
        private final static Map<String, TxType> CONSTANTS = new HashMap<String, TxType>();

        static {
            for (TxType c : values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        private TxType(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static TxType fromValue(String value) {
            TxType constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

    private TransactionDetails transactionDetails;
    private PosDetailsResponse posDetails;
    /**
     * statusDetails
     * <p>
     * 
     * 
     */
    private StatusDetails statusDetails;
    /**
     * originTxDetails
     * <p>
     * This object is only applicable if the `txType` is REFUND.
     * 
     */
    private OriginTxDetails originTxDetails;
    /**
     * promoDetails
     * <p>
     * This is only applicable if the `txType` is PAYMENT, unless otherwise stated.
     * 
     */
    private PromoDetails promoDetails;
    /**
     * metadata
     * <p>
     * 
     * 
     */
    private Metadata metadata;

    public TransactionDetails getTransactionDetails() {
        return transactionDetails;
    }

    public void setTransactionDetails(TransactionDetails transactionDetails) {
        this.transactionDetails = transactionDetails;
    }

    public PosDetailsResponse getPosDetails() {
        return posDetails;
    }

    @JsonSetter("POSDetails")
    public void setPOSDetails(PosDetailsResponse posDetails) {
        this.posDetails = posDetails;
    }

    /**
     * statusDetails
     * <p>
     * 
     * 
     */
    public StatusDetails getStatusDetails() {
        return statusDetails;
    }

    /**
     * statusDetails
     * <p>
     * 
     * 
     */
    public void setStatusDetails(StatusDetails statusDetails) {
        this.statusDetails = statusDetails;
    }

    /**
     * originTxDetails
     * <p>
     * This object is only applicable if the `txType` is REFUND.
     * 
     */
    public OriginTxDetails getOriginTxDetails() {
        return originTxDetails;
    }

    /**
     * originTxDetails
     * <p>
     * This object is only applicable if the `txType` is REFUND.
     * 
     */
    public void setOriginTxDetails(OriginTxDetails originTxDetails) {
        this.originTxDetails = originTxDetails;
    }

    /**
     * promoDetails
     * <p>
     * This is only applicable if the `txType` is PAYMENT, unless otherwise stated.
     * 
     */
    public PromoDetails getPromoDetails() {
        return promoDetails;
    }

    /**
     * promoDetails
     * <p>
     * This is only applicable if the `txType` is PAYMENT, unless otherwise stated.
     * 
     */
    public void setPromoDetails(PromoDetails promoDetails) {
        this.promoDetails = promoDetails;
    }

    /**
     * metadata
     * <p>
     * 
     * 
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * metadata
     * <p>
     * 
     * 
     */
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(PosInquiryResponse.class.getName()).append('@')
                .append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("transactionDetails");
        sb.append('=');
        sb.append(((this.transactionDetails == null) ? "<null>" : this.transactionDetails));
        sb.append(',');
        sb.append("posDetails");
        sb.append('=');
        sb.append(((this.posDetails == null) ? "<null>" : this.posDetails));
        sb.append(',');
        sb.append("statusDetails");
        sb.append('=');
        sb.append(((this.statusDetails == null) ? "<null>" : this.statusDetails));
        sb.append(',');
        sb.append("originTxDetails");
        sb.append('=');
        sb.append(((this.originTxDetails == null) ? "<null>" : this.originTxDetails));
        sb.append(',');
        sb.append("promoDetails");
        sb.append('=');
        sb.append(((this.promoDetails == null) ? "<null>" : this.promoDetails));
        sb.append(',');
        sb.append("metadata");
        sb.append('=');
        sb.append(((this.metadata == null) ? "<null>" : this.metadata));
        sb.append(',');
        if (sb.charAt((sb.length() - 1)) == ',') {
            sb.setCharAt((sb.length() - 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result * 31) + ((this.transactionDetails == null) ? 0 : this.transactionDetails.hashCode()));
        result = ((result * 31) + ((this.metadata == null) ? 0 : this.metadata.hashCode()));
        result = ((result * 31) + ((this.originTxDetails == null) ? 0 : this.originTxDetails.hashCode()));
        result = ((result * 31) + ((this.statusDetails == null) ? 0 : this.statusDetails.hashCode()));
        result = ((result * 31) + ((this.posDetails == null) ? 0 : this.posDetails.hashCode()));
        result = ((result * 31) + ((this.promoDetails == null) ? 0 : this.promoDetails.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof PosInquiryResponse) == false) {
            return false;
        }
        PosInquiryResponse rhs = ((PosInquiryResponse) other);
        return (((((((this.transactionDetails == rhs.transactionDetails)
                || ((this.transactionDetails != null) && this.transactionDetails.equals(rhs.transactionDetails)))
                && ((this.metadata == rhs.metadata) || ((this.metadata != null) && this.metadata.equals(rhs.metadata))))
                && ((this.originTxDetails == rhs.originTxDetails)
                        || ((this.originTxDetails != null) && this.originTxDetails.equals(rhs.originTxDetails))))
                && ((this.statusDetails == rhs.statusDetails)
                        || ((this.statusDetails != null) && this.statusDetails.equals(rhs.statusDetails))))
                && ((this.posDetails == rhs.posDetails)
                        || ((this.posDetails != null) && this.posDetails.equals(rhs.posDetails))))
                && ((this.promoDetails == rhs.promoDetails)
                        || ((this.promoDetails != null) && this.promoDetails.equals(rhs.promoDetails))));
    }

}
